# Generated by Django 3.2.5 on 2021-07-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('full_name', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
