# Generated by Django 4.1.1 on 2022-09-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
