# Generated by Django 4.1.1 on 2022-09-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_listener'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
