# Generated by Django 4.1.6 on 2023-02-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_account_email_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestgroup',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
