# Generated by Django 4.1.6 on 2023-07-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_contestproblem_binary_pass_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='try_penalty',
            field=models.IntegerField(default=20),
        ),
    ]
