#cc_binary(
#    name = "bad_programs_test",
#    srcs = ["bad_programs_test.cc"],
#    copts = ["-Iexternal/gtest/include"],
#    deps = [
#        "@gtest//:gtest",
#        "//util:test_main",
#        "//container/outside"
#    ],
#    data = [":programs"]
#)
