cc_binary(
    name = "omogenexec_cli",
    srcs = ["main.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//api:omogenexec_cc_proto",
        "//external:gflags",
        "//external:glog",
        "//util",
        "@com_google_absl//absl/strings",
    ],
)
