cc_binary(
        name = "cli",
        visibility = ["//visibility:public"],
		srcs = ["main.cc"],
        deps = [
                "//container:container",
                "//proto:omogenexec_cc_proto",
        ],
)
