cc_library(
        name = "util",
        visibility = ["//visibility:public"],
        srcs = ["log.cc", "error.cc"],
        hdrs = ["log.h", "error.h"],
        deps = [
                "//external:gflags",
        ],
)
