cc_library(
        name = "logger",
        visibility = ["//visibility:public"],
        srcs = ["logger.cpp"],
        hdrs = ["logger.h"],
        deps = [
                "//external:gflags",
        ],
)
