load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
		name = "omogenexec_cc_proto",
		protos = ["omogenexec.proto"],
		with_grpc = True,
		visibility = ["//visibility:public"],
		)
