#!/bin/sh -e

### BEGIN INIT INFO
# Provides:             omogenexecd
# Required-Start:       $local_fs $network $time
# Required-Stop:        $local_fs $network $time
# Should-Start:         $syslog
# Should-Stop:          $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Omogenexec container server
### END INIT INFO

. /lib/lsb/init-functions

EXECUTABLE=/usr/bin/omogenexec_server
USERNAME=omogenexec
SERVICE=omogenexecd
PIDFILE=/var/run/${SERVICE}.pid

start() {
    log_success_msg "Starting ${SERVICE}"
    mkdir -p /sys/fs/cgroup/cpuacct/omogencontain
    mkdir -p /sys/fs/cgroup/cpuset/omogencontain
    mkdir -p /sys/fs/cgroup/pids/omogencontain
    mkdir -p /sys/fs/cgroup/memory/omogencontain
    chown omogenexec:omogenexec /sys/fs/cgroup/cpuacct/omogencontain
    chown omogenexec:omogenexec /sys/fs/cgroup/cpuset/omogencontain
    chown omogenexec:omogenexec /sys/fs/cgroup/pids/omogencontain
    chown omogenexec:omogenexec /sys/fs/cgroup/memory/omogencontain
    start-stop-daemon --start -b -m --pidfile ${PIDFILE} --chuid ${USERNAME} --user ${USERNAME} --startas ${EXECUTABLE}
    RET=$?
    if [ $RET -ne 0 ]; then
        log_failure_msg "Failed to start ${SERVICE}"
        exit ${RET}
    fi
}

status() {
    start-stop-daemon --status --pidfile ${PIDFILE} --chuid ${USERNAME} --user ${USERNAME} --startas ${EXECUTABLE}
    RET=$?
    if [ ${RET} -ne 0 ]; then
        log_success_msg "${SERVICE} is NOT running"
        exit ${RET}
    fi
}

stop() {
    log_success_msg "Stopping ${SERVICE}"
    start-stop-daemon --stop --pidfile ${PIDFILE} --chuid ${USERNAME} --user ${USERNAME} --startas ${EXECUTABLE}
    RET=$?
    rm -f ${PIDFILE}
    if [ ${RET} -ne 0 ]; then
        log_warning_msg "${SERVICE} is not running"
        exit 0
    fi
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    status)
        status
        ;;

    *)
        log_warning_msg ""
        log_warning_msg "Usage : `basename $0` {start | stop | status }"
        log_warning_msg ""
        exit 3
        ;;
esac

exit 0

