cc_binary(
    name = "omogenjudge-setquota",
    srcs = ["main.cc"],
    visibility = [
        "//sandbox:__subpackages__",
    ],
    deps = [
        "//util/cpp",
        "@com_google_absl//absl/strings",
    ],
)
