filegroup(
    name = "resources",
    srcs = glob([
        "vs/**/*",
        "**/*.js",
        "**/*.css",
        "**/*.svg",
        "**/*.png",
    ]),
    visibility = ["//frontend:__subpackages__"],
)
