cc_binary(
    name = "omogenjudge-permissionfixer",
    srcs = ["fixer.cpp"],
    visibility = [
        "//localjudge:__subpackages__",
    ],
    deps = [
        "@com_google_absl//absl/strings",
    ],
)
