cc_binary(
    name = "omogenjudge-sandboxc",
    srcs = ["sandboxclear.cpp"],
    visibility = [
        "//sandbox:__subpackages__",
    ],
    deps = [
        "@com_google_absl//absl/strings",
    ],
)
